### ISSUE TITLE
SSO Support

### ISSUE THREAD

**Issue by kernwig** [oslabs-beta/helios#40]
The "Add Helios CloudFormation stack to AWS" link goes to a login page for individual accounts, making this tool unusable for enterprise applications.

Please provide an public S3 URL or copy of the CloudFormation template for use, both for SSO/Control Tower accounts, and for auditing of policies.

**Comment by jackiedouglass** [comment]
Hi there! I just added a copy of the template to the public folder. Just be sure to update the AWS account the Cloud Formation stack role will be associated with on line 13 to yours. There's also now a comment on the register page letting you know how to update the URL to associate it with a template of your own creation, just be sure to upload your template to an S3 bucket and use that link instead.

Please let us know if you encounter any other issues.
